# Generated by Django 2.0 on 2018-07-23 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_wallet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'British pound'), ('HRK', 'Croatian kuna'), ('USD', 'United States dollar'), ('CHF', 'Swiss franc')], max_length=5)),
                ('category', models.CharField(choices=[('paycheck', 'Paycheck'), ('gasoline', 'Car gas'), ('charity', 'Charity (e.g. donations)'), ('clothing', 'Clothes'), ('groceries', 'Groceries'), ('gifts', 'Gifts'), ('healthcare', 'Healthcare'), ('household', 'Household (e.g. rennovations)'), ('insurance', 'Insurance costs'), ('leisure_hobbies', 'Leisure and hobbies'), ('utilities', 'Utilities (e.g. electricity bills)'), ('vacation', 'Vacation')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'British pound'), ('HRK', 'Croatian kuna'), ('USD', 'United States dollar'), ('CHF', 'Swiss franc')], max_length=5),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.Wallet'),
        ),
    ]
