# Generated by Django 2.0 on 2018-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20180723_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('paycheck', 'Paycheck'), ('gasoline', 'Car gas'), ('charity', 'Charity (e.g. donations)'), ('clothing', 'Clothes'), ('groceries', 'Groceries'), ('gifts', 'Gifts'), ('healthcare', 'Healthcare'), ('household', 'Household (e.g. rennovations)'), ('insurance', 'Insurance costs'), ('leisure_hobbies', 'Leisure and hobbies'), ('utilities', 'Utilities (e.g. electricity bills)'), ('vacation', 'Vacation'), ('other', 'Other')], max_length=20),
        ),
    ]
